### ISSUE TITLE
Deploy to Kentico Marketplace?

### ISSUE THREAD

**Issue by axeljlarsen** [Kentico/kentico-amp#19]
I'm very unfamiliar with standard practices with submitting git "issues" but i couldn't find a way to just contact someone directly with this question:

Would it be possible to deploy this as a module within the Kentico Markeplace and if not, is it possible to export this module from one kentico instance and import it via the Kentico Portal in another instance of the same exact version?

**Comment by petrsvihlik** [comment]
Hi @axeljlarsen , in fact it is a standard Kentico Module. You can follow these instructions to install the module: https://docs.kentico.com/k11/custom-development/creating-custom-modules/creating-installation-packages-for-modules/installing-modules-from-installation-packages#Installingmodulesfrominstallationpackages-AddingthemoduleinstallationpackagetotheKenticosolution

We have added it to the [open-source section on DevNet](https://devnet.kentico.com/open-source) - could take a few minutes to appear there.

We could consider adding it to the marketplace as well but I think it's redundant.

What are your thoughts @kentico-danielak ?

**Comment by kentico-danielak** [comment]
Hi @axeljlarsen,
before any item is published to Kentico Marketplace, proper testing and security review must be done. I was informed that Kentico AMP was already tested but we are still waiting for the security review.

**Comment by kentico-danielak** [comment]
Hi, 
AMP Module was published to Kentico Marketplace https://devnet.kentico.com/marketplace/modules/kentico-amp
