### ISSUE TITLE
Incorrect usage of CMSFriendlyURLExtension

### ISSUE THREAD

**Issue by OndrejVrsan** [Kentico/kentico-amp#27]
The `CMSFriendlyURLExtension` setting can be one extension (e.g. `.aspx`), but it can also be list of extensions separated by semicolon (e.g. `.aspx;.html;.htm`).

The list of extensions is not taken into account in code using this setting, e.g.
https://github.com/Kentico/kentico-amp/blob/046b7d43f04e45c42b8361bcebceaa1af71ad1c4/Kentico.AcceleratedMobilePages/AmpFilter.cs#L73

Review usage of the setting and in case of more extension, use just first one.

**Comment by petrsvihlik** [comment]
resolved in #31
