### ISSUE TITLE
Can't submit Kentico on-line form on AMP page

### ISSUE THREAD

**Issue by axeljlarsen** [Kentico/kentico-amp#28]
I'm getting the following error in the browser's console window when a basic Kentico form is submitted on an AMP.

Response must contain the AMP-Access-Control-Allow-Source-Origin header

From the documentation, I'm not seeing any steps to allow basic form submissions on an AMP. I also see that on my phone, the amp.advantage.kentico.com site's search functionality leads to a 404 page so I'm not currently seeing any working examples of a Kentico on-line form on an AMP.

Any help or insight you can provide would be greatly appreciated.

<img width="1259" alt="amp issue" src="https://user-images.githubusercontent.com/7439941/37836154-cad9f316-2e7f-11e8-98bf-f38941533bfe.png">
<img width="597" alt="amp issue 2" src="https://user-images.githubusercontent.com/7439941/37836426-653abb34-2e80-11e8-87f7-5f655f928d16.png">

**Comment by OndrejVrsan** [comment]
Cloned to internal issue log as PLATFORM-11940

**Comment by axeljlarsen** [comment]
I hate to be more of a bother but I would **_really_** appreciate if this fix could be applied to the module compatible with version 10 of Kentico.

**Comment by OndrejVrsan** [comment]
Hi @axeljlarsen , 

Regarding the support for version 10 - we only provide support for the last released version of Kentico, which is currently version 11. However, you are free to fork this module and implement the feature for Kentico 10.

Our team investigated the reported issue and found out it is not a bug, but a feature request. 
As you can see under the [Scenarios covered by AMP filter](https://github.com/Kentico/kentico-amp/blob/0195da1a0be1f58896b0eb01dd2d5fa5f26f940c/README.md#scenarios-covered-by-amp-filter), only regular HTML pages without interactive elements are supported. The AMP module support for the `form` tag is intended only for static pages (all web forms pages contain, by default, a 'form' tag they use to store metadata and viewstate information). This is also the reason why CORS is not enabled by the AMP filter module itself.
We decided to [reformulate](https://github.com/Kentico/kentico-amp/blob/ed2702387e01027e18501bb06520088bea76d3ae/README.md#scenarios-covered-by-the-amp-filter) the paragraph describing covered scenarios (linked above) to make them clearer.

To enable CORS, please refer to the [CORS in AMP documentation](https://www.ampproject.org/docs/fundamentals/amp-cors-requests), which covers the implementation of CORS headers in AMP.

For AMP to work correctly with online form, changes on both the server and client side are needed. See the [amp-form documentation](https://www.ampproject.org/docs/reference/components/amp-form) for more details.
